#!/usr/bin/env python3
"""Regenerate data/meta.js — a timestamp for the "data refreshed" UI badge.

Deliberately modest: it records when the pipeline (build_data.py +
build_extras.py + build_cables.py) last ran successfully, not a per-source
claim we can't actually verify (the underlying sources update on their own
schedules, some daily, some yearly). Run this last, after check_data.py has
passed.

Usage:
    python3 scripts/build_meta.py
"""
import json
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def main():
    meta = {"generated": datetime.now(timezone.utc).strftime("%Y-%m-%d")}
    js = ("// Generated by scripts/build_meta.py — do not edit by hand.\n"
          "// Timestamp for the \"data refreshed\" UI badge.\n"
          "window.META=" + json.dumps(meta, separators=(",", ":")) + ";\n")
    target = REPO / "data" / "meta.js"
    target.write_text(js)
    print(f"wrote {target} — generated {meta['generated']}")


if __name__ == "__main__":
    main()
