#!/usr/bin/env python3
"""Regenerate data/cables.js — submarine cable routes with ready-for-service years.

Source: TeleGeography's live submarinecablemap.com v3 API. The cable list
and geometry come from two bulk endpoints; ready-for-service year and owners
live in one small JSON per cable, fetched concurrently.

Usage:
    python3 scripts/build_cables.py

No dependencies beyond the Python standard library.
"""
import json
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

API = "https://www.submarinecablemap.com/api/v3/cable/"
REPO = Path(__file__).resolve().parent.parent
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0 Safari/537.36")


def fetch_json(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    for attempt in range(3):
        try:
            with urllib.request.urlopen(req, timeout=60) as r:
                return json.load(r)
        except Exception:
            if attempt == 2:
                raise


def simplify(points, tol=0.15):
    """Drop points that don't deviate from the running line by more than
    tol degrees — cheap perpendicular-ish thinning, good enough at map scale."""
    if len(points) <= 2:
        return points
    out = [points[0]]
    for p in points[1:-1]:
        lx, ly = out[-1]
        if abs(p[0] - lx) > tol or abs(p[1] - ly) > tol:
            out.append(p)
    out.append(points[-1])
    return out


def main():
    print("downloading cable index ...")
    index = fetch_json(API + "all.json")
    print("downloading cable geometry ...")
    geo = fetch_json(API + "cable-geo.json")

    segs_by_id = {}
    for f in geo["features"]:
        cid = f["properties"]["id"]
        segs_by_id.setdefault(cid, [])
        for line in f["geometry"]["coordinates"]:
            pts = [[round(float(lon), 3), round(float(lat), 3)] for lon, lat in line]
            segs_by_id[cid].append(simplify(pts))

    print(f"downloading {len(index)} cable detail files ...")
    with ThreadPoolExecutor(max_workers=8) as pool:
        details = list(pool.map(
            lambda c: fetch_json(API + c["id"] + ".json"), index))

    cables, planned = [], 0
    for c in details:
        rfs = c.get("rfs_year")
        segs = segs_by_id.get(c["id"])
        if c.get("is_planned"):
            planned += 1
            continue
        if not segs or not rfs:
            continue
        cables.append({
            "id": c["id"], "name": c["name"], "rfs": int(rfs),
            "owners": c.get("owners") or None, "segs": segs,
        })
    cables.sort(key=lambda c: c["rfs"])

    js = ("// Generated by scripts/build_cables.py — do not edit by hand.\n"
          "// Source: TeleGeography submarinecablemap.com v3 API (live).\n"
          "// In-service cables only; planned builds are excluded.\n"
          "window.CABLES=" + json.dumps(cables, separators=(",", ":")) + ";\n")
    target = REPO / "data" / "cables.js"
    target.write_text(js)
    years = [c["rfs"] for c in cables]
    print(f"wrote {target} — {len(cables)} cables, RFS {min(years)}–{max(years)}"
          f" ({planned} planned builds excluded)")


if __name__ == "__main__":
    main()
