#!/usr/bin/env python3
"""Regenerate data/cables.js — submarine cable routes with ready-for-service years.

Source: a public mirror of TeleGeography's submarinecablemap.com dataset
(github.com/delusan/www.submarinecablemap.com). It's a fixed historical
snapshot (RFS years up to ~2015) rather than a live feed, so the layer reads
as "the network as it was built through the mid-2010s," not up to the
present day — noted in the UI copy and README.

Usage:
    python3 scripts/build_cables.py
"""
import json
import re
import urllib.request
from pathlib import Path

BASE = ("https://raw.githubusercontent.com/delusan/www.submarinecablemap.com"
         "/master/public/javascripts/cables/")
REPO = Path(__file__).resolve().parent.parent


def fetch_json(name):
    req = urllib.request.Request(BASE + name, headers={"User-Agent": "internet-adoption-map data pipeline"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.load(r)


def parse_rfs(text):
    m = re.search(r"(19|20)\d{2}", text or "")
    return int(m.group()) if m else None


def simplify(points, tol=0.15):
    """Drop points that don't deviate from the running line by more than
    tol degrees — cheap perpendicular-ish thinning, good enough at map scale."""
    if len(points) <= 2:
        return points
    out = [points[0]]
    for p in points[1:-1]:
        lx, ly = out[-1]
        if abs(p[0] - lx) > tol or abs(p[1] - ly) > tol:
            out.append(p)
    out.append(points[-1])
    return out


def main():
    print("downloading cable index ...")
    meta = fetch_json("all.json")
    print("downloading cable geometry ...")
    geo = fetch_json("cables-geo.json")

    segs_by_id = {}
    for f in geo["features"]:
        cid = f["properties"]["id"]
        segs_by_id.setdefault(cid, [])
        for line in f["geometry"]["coordinates"]:
            pts = [[round(float(lon), 3), round(float(lat), 3)] for lon, lat in line]
            segs_by_id[cid].append(simplify(pts))

    cables = []
    for c in meta:
        cid = c["id"]
        rfs = parse_rfs(c.get("rfs"))
        segs = segs_by_id.get(cid)
        if not segs or rfs is None:
            continue
        cables.append({
            "id": cid, "name": c["name"], "rfs": rfs,
            "owners": c.get("owners") or None, "segs": segs,
        })
    cables.sort(key=lambda c: c["rfs"])

    js = ("// Generated by scripts/build_cables.py — do not edit by hand.\n"
          "// Source: public mirror of TeleGeography's submarine cable map\n"
          "// (github.com/delusan/www.submarinecablemap.com) — a historical\n"
          "// snapshot; ready-for-service years run up to ~2015.\n"
          "window.CABLES=" + json.dumps(cables, separators=(",", ":")) + ";\n")
    target = REPO / "data" / "cables.js"
    target.write_text(js)
    years = [c["rfs"] for c in cables]
    print(f"wrote {target} — {len(cables)} cables, RFS {min(years)}–{max(years)}")


if __name__ == "__main__":
    main()
